Fix for cl.exe with LLVM backend
When compiling with LLVM 6's cl.exe frontend (\LLVM\msbuild-bin\cl.exe) using LLVM's backend on Windows, the following compiler error is emitted:
boost\boost/type_traits/has_trivial_move_assign.hpp(49): error : no template named 'is_assignable'; did you mean 'std::is_assignable'?

The reason is that <boost/type_traits/is_assignable.hpp> is not included, because __clang__ is not defined.

The proposed PR ensures that is_assignable.hpp is included in this situation.